let Airline=[
    {
        id:0,
        AirlineCompanies:"ISR",
        country:"israel",
        planes:15,
        available:4
    },
    {
        id:1,
        AirlineCompanies:"BAL",
        country:"belgium",
        planes:40,
        available:20
    },
    {
        id:2,
        AirlineCompanies:"BZL",
        country:"brazil",
        planes:20,
        available:12
    },
    {
        id:3,
        AirlineCompanies:"ETH",
        country:"ethiopia",
        planes:26,
        available:8
    },
    {
        id:4,
        AirlineCompanies:"URU",
        country:"uruguay",
        planes:15,
        available:7
    },
    {
        id:5,
        AirlineCompanies:"ILY",
        country:"italy",
        planes:55,
        available:38
    },
    {
        id:6,
        AirlineCompanies:"BUL",
        country:"bulgaria",
        planes:28,
        available:15
    },
    {
        id:7,
        AirlineCompanies:"RMI",
        country:"romania",
        planes:16,
        available:10
    },
    {
        id:8,
        AirlineCompanies:"USA",
        country:"usa states",
        planes:70,
        available:55
    },
    {
        id:9,
        AirlineCompanies:"UGD",
        country:"uganda",
        planes:32,
        available:19
    }
];

module.exports=Airline;